//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinoVideoProkat_K.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Purchases = new HashSet<Purchase>();
            this.Rents = new HashSet<Rent>();
        }
    
        public int IdFilm { get; set; }
        public string NameFilm { get; set; }
        public string Author { get; set; }
        public string Comment { get; set; }
        public string Producer { get; set; }
        public string Company { get; set; }
        public Nullable<int> Year { get; set; }
        public string Land { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Rate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rents { get; set; }
    }
}
