//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinoVideoProkat_K.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Id { get; set; }
        public Nullable<int> IdProvider { get; set; }
        public Nullable<int> IdFilm { get; set; }
        public Nullable<System.DateTime> DateBuy { get; set; }
        public Nullable<decimal> Summ { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
